// Vehicle data
const vehicles = [
  {
    id: 1,
    name: "Mercedes",
    category: "sedan",
    price: 35,
    period: "per day",
    passengers: 5,
    bags: 3,
    transmission: "Automatic",
    image: "Mercedes Sedan",
  },
  {
    id: 2,
    name: "Mercedes",
    category: "suv",
    price: 60,
    period: "per day",
    passengers: 7,
    bags: 5,
    transmission: "Automatic",
    image: "Mercedes SUV",
  },
  {
    id: 3,
    name: "Mercedes",
    category: "premium",
    price: 85,
    period: "per day",
    passengers: 4,
    bags: 2,
    transmission: "Automatic",
    image: "Mercedes Coupe",
  },
  {
    id: 4,
    name: "Porsche",
    category: "premium",
    price: 120,
    period: "per day",
    passengers: 2,
    bags: 1,
    transmission: "Manual",
    image: "Porsche Sports",
  },
  {
    id: 5,
    name: "Toyota",
    category: "crossover",
    price: 45,
    period: "per day",
    passengers: 5,
    bags: 4,
    transmission: "Automatic",
    image: "Toyota Crossover",
  },
  {
    id: 6,
    name: "Porsche",
    category: "premium",
    price: 150,
    period: "per day",
    passengers: 2,
    bags: 1,
    transmission: "Automatic",
    image: "Porsche Luxury",
  },
  {
    id: 7,
    name: "Mercedes",
    category: "van",
    price: 75,
    period: "per day",
    passengers: 8,
    bags: 6,
    transmission: "Automatic",
    image: "Mercedes Van",
  },
  {
    id: 8,
    name: "Toyota",
    category: "sedan",
    price: 40,
    period: "per day",
    passengers: 5,
    bags: 3,
    transmission: "Automatic",
    image: "Toyota Sedan",
  },
  {
    id: 9,
    name: "Maybach",
    category: "premium",
    price: 200,
    period: "per day",
    passengers: 4,
    bags: 3,
    transmission: "Automatic",
    image: "Maybach Luxury",
  },
];
